version: "3.7"

services:
  app:
    image: gradle:5.6.3-jdk11
    working_dir: /app
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
    networks:
      - app_net
    env_file:
      - docker.env
    ports:
      - 8080:8080
      - 5005:5005
    command: gradle bootRun
    depends_on:
      - db

  test:
    image: gradle:5.6.3-jdk11
    working_dir: /app
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_net
    command: gradle clean check

  db:
    image: mysql:5.7
    restart: always
    privileged: true
    environment:
      MYSQL_USER: scaffold_rw
      MYSQL_PASSWORD: password10
      MYSQL_DATABASE: scaffold_db
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - app_net
    volumes:
      - ./mysql/conf:/etc/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

networks:
  app_net:

volumes:
  gradle-cache:
  db-cache:
