spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scaffold_db?characterEncoding=utf8&useSSL=false
    username: scaffold_rw
    password: password10
  jpa:
    show-sql: true
server:
  port: 8080
